### ISSUE TITLE
Execution failed for task ':sample:transformClassesWithJavaAssistTransformForDebug'.

### ISSUE THREAD

**Issue by kaleai** [xiaobo0113/MethodTimeCost#2]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:transformClassesWithJavaAssistTransformForDebug'.
> javassist.NotFoundException: C:\Users\46041\Desktop\MethodTimeCost-master\MethodTimeCost-master\sample\build\intermediates\transforms\JavaAssistTransform\debug\folders\1\1f\java_assist_dir\com\xiaobo\example\java_assist\TimeUtil

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sample:transformClassesWithJavaAssistTransformForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)

**Comment by kaleai** [comment]
![image](https://user-images.githubusercontent.com/9552155/31482641-af25c26a-af5b-11e7-861c-d3ca40a70e17.png)

**Comment by xiaobo0113** [comment]
please try it again. if still can not compile, please let me know.

**Comment by Corey3213** [comment]
my project has eight modules,but now is only support application module,can not support other modules, what should i do?  (my english is very poor, I hope you can understand)
